nordtheme/jetbrains

src/nord-intellij-idea-syntax.icls
> Closes #24
Related to #10
The background colors of the debugging- and diff views were too bright making the text unreadable. This PR increases the transparency of the colors to provide a better legibility.
<p align="center"><strong>Before</strong><br><img src="https://user-images.githubusercontent.com/7836623/31133249-3a7664a4-a85f-11e7-931b-f3175893f1fc.png"/><br><strong>After</strong><br><img src="https://user-images.githubusercontent.com/7836623/31133259-400eabce-a85f-11e7-8ba3-0408c3ccd223.png"/></p>
=> Reduce transparency for debug- and diff background

src/nord-intellij-idea-syntax.icls
> Closes #26
Related to #10
Previews with the automatic highlighting on the left side and with a selection on the right side.
<p align="center"><strong>Before</strong><br><img src="https://user-images.githubusercontent.com/7836623/31134633-f36df0be-a862-11e7-8662-be190827fbb4.png"/><br><strong>After</strong><br><img src="https://user-images.githubusercontent.com/7836623/31134652-05e9583c-a863-11e7-96ab-3c81f394034e.png"/></p>
=> Remove background from identifier under caret

src/nord-jetbrains-editor.icls
> Bound to https://github.com/arcticicestudio/nord/issues/94
> Resolves #41 
This issue will implement the increase of the comment color (`nord3`) brightness by 10% from a lightness level of ~35% to ~45%.
➜ Please see https://github.com/arcticicestudio/nord/issues/94 for all details about this design change decision.
=> Comment Color Brightness

src/nord.theme.json
> Resolves #47 
The [File Colors][fc] are used to distingush between project files, folders or packages of specific scopes. Unfortunately the theme API doesn't allow (yet) to specify the target for the color like e.g. background or only foreground.
With the previous colors (100% opacity) this resulted in too bright highlighted backgrounds making most labels unreadable and destroying the themes overall appearance.
They color's opacity has now been changed to 10% which is still enough to be recognizable and doesn't affects the readability of labels.
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/58237656-f0579d80-7d45-11e9-9d6a-9ae9923299c5.png"></p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/58237738-1e3ce200-7d46-11e9-8364-6 …
=> Reduced opacity for "File Colors" UI theme keys

resources/themes/nord.xml
> Resolves #52 
Before the new UI theme API was released the editor color scheme provided multiple theme keys to also style some UI elements like the editor notifications ([`NOTIFICATION_BACKGROUND`][key-def] like also defined in the [default bundled Darcula editor color scheme][decs]).
The key allows to style the background color of notifications from the editor that are placed right below the tab bar at the top of the editor.
Previously `nord4` was used that made the color almost unreadable because by default a low contrast foreground is used.
This has now been changed to use `nord3` making the actual text content readable again.
<p align="center"><strong>Before</strong></p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/59462569-4c34b400-8e24-11e9-9551-b1c …
=> Editor Notification Background Color

resources/themes/nord.xml
> Resolves #60 
A line that contained both a syntax error as well as a _IntelliJ Code Inspection_ (`ERRORS_ATTRIBUTES` editor scheme key) error was unreadable because both error detection scopes/types applied their different highlighting styles resulting in a background and foreground color colorized with `nord11`. This made it impossible to read the text.
<p align="center">Highlighting resulting in unreadable text when combined with error text</p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/59548537-20fbb300-8f51-11e9-98b3-ed48888f4978.png"></p>
Some tests using a opacity of 60% for `nord11` as background color instead resulted in a “dirty redish“ color due to the miy with the base editor background color.
<p align="center">Reduced opacity of 60%</p>
<p …
=> Improve style for lines with both syntax and code inspection errors

resources/themes/nord.xml
> Resolves #63 
The “General“ editor scheme section provides a option to style _deprecated symbols that are marked for removal_.
The new `MARKED_FOR_REMOVAL_ATTRIBUTES` key has been added using a `strikethrough` effect style colorized with `nord11` to draw more attention to such elements.
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/59548762-260e3180-8f54-11e9-90c7-ec5a6a4ce92b.png"></p>
=> Styles for deprecated symbols marked for removal

resources/themes/nord.xml
> Resolves #69 
IntelliJ/Goland version 2019.2 [introduced support for 20+ languages][rl] out-of-the-box by integrating [TextMate][tm] schemes.
Unfortunately this resulted in a change for existing theme definition where some editor color scheme keys that previously inherited the best matching global key now used the attributes defined by the parent theme _Darcula_. Therefore Nord's highlighting for Go broke and required to explicitly define the values for some attributes in order to achieve the same highlight like in previous versions that are matching Nord's style guidelines.
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/62239717-b81fab80-b3d5-11e9-8e17-3b9d7fe3424e.png" /></p>
<p align="center">After</p>
<p align="center"><img …
=> Go syntax highlighting support for IntelliJ/Goland 2019.2

resources/themes/nord.xml
> Resolves #73 
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/62275216-cb686080-b441-11e9-9898-2024a8122a51.png"/></p>
<p align="center">After</p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/62275215-cb686080-b441-11e9-8a35-9070cad89406.png"/></p>
=> Console log output

resources/themes/nord.xml
> Resolves #79 
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/62284066-33737280-b453-11e9-9f26-5146eeb3ef62.png"/></p>
<p align="center">After</p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/62284065-33737280-b453-11e9-9eaa-658ce5e1350c.png"/></p>
=> Use `nord8` for Markdown link titles

resources/themes/nord.xml
> Resolves #81 
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/62284838-b77a2a00-b454-11e9-85f2-fba1a3f52304.png"/></p>
<p align="center">After</p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/62284837-b77a2a00-b454-11e9-8eea-d12f2e611a73.png"/></p>
=> Normal styles for TypeScript "type guarded" variables

resources/themes/nord.xml
> Resolves #35 
Added support for the [official Python plugin][plug] that adds syntax highlighting for Python as well as [Jupyter][j] and [Mako Templates][m] and is equal to the [PyCharm Professional Edition][pyc].
<p align="center"><strong>Python</strong></p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/62292274-6410d780-b466-11e9-968e-3887719ca335.png"/></p>
<p align="center"><strong>Jupyter</strong></p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/62292272-63784100-b466-11e9-9805-d68cac0d32a8.png"/></p>
<p align="center"><strong>Mako Templates</strong></p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/62292273-63784100-b466-11e9-88d1-5313754c46be.png"/></p>
<p …
=> Python Plugin (PyCharm Professional Edition) Support

resources/themes/nord.xml, src/nord.theme.json
> Resolves #86 
<p align="center"><strong>Before</strong></p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/62307619-35095e80-b484-11e9-9123-2c3142fa4e11.png"/></p>
<p align="center"><strong>After</strong></p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/62307795-874a7f80-b484-11e9-89a1-d33bb942bab6.png"/></p>
<p align="center"><strong>Before</strong></p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/62307689-566a4a80-b484-11e9-8980-7d4b57e6253c.png"/></p>
<p align="center"><strong>After</strong></p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/62307793-86b1e900-b484-11e9-9b60-a4458cc5b12b.png"/></p>
<p align="center"><strong>Before</strong></p>
<p …
=> Support 2019.2 deprecation replacement UI theme keys

src/nord.theme.json
> Fixes #88 
In [v0.8.0][] some new UI theme keys have been added and deprecated ones modified or removed through #86 and PR #87. This included the `ui.CompletionPopup.nonFocusedMask` key that has been set to `nord0` without a alpha layer value. Since the auto completion popup of IntelliSense if not focused but the editor itself, the overlay mask gets applied. As soon as the up or down arrow keys are pressed the popup gets the focus and therefore the mask gets removed showing the list items with correct styles.
The key has been removed, the popup should be shown the same like in focused state for better readable text and easy recognition of the desired auto complete entry.
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/62409939-e3 …
=> Fix unreadable completion popup list items in non-focused state

resources/themes/nord.xml
Related to #69, #70
Fixes #108 
---
Like already documented and fixed in #70, IntelliJ/Goland version 2019.3 also [changes in Go's syntax highlight for the default bundled color schemes][goland].
This again requires to explicitly define the values for some attributes in order to achieve the same highlight like in previous versions that are matching Nord's style guidelines.
Unfortunately this resulted again in a change for existing theme definition where some editor color scheme keys that previously inherited the best matching global key now used the attributes defined by the parent theme _Darcula_. Therefore Nord's highlighting for Go broke again and required to explicitly define the values for some attributes in order to achieve the same highlight like in previous versions that are …
=> Go syntax highlighting support for IntelliJ/Goland 2019.3

resources/themes/nord.xml
During the transition from the old to the new theme API the font style
for RegEx braces and brackets were changed to _italic_.
It looks way cleaner and less distracting without italic font style especially because it is mixed with normal styles.
<div align="center"><p><strong>Before</strong></p></div>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/70891834-58264c00-1fe8-11ea-8ff8-c55c2b3cb162.png"/></p>
<div align="center"><p><strong>After</strong></p></div>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/70891833-58264c00-1fe8-11ea-9f27-a7b90a411ff4.png"/></p>
---
Resolves #107
=> Remove italic font style for RegEx braces and brackets

resources/themes/nord.xml
Fixes #115 
---
As of IDE versions 2019.3.x, some TypeScript and JavaScript syntax elements were not highlighted correctly. The following elements inherited the colors from the _Darcula_ parent scheme instead of the language defaults defined by Nord:
- _Global function_
- _Global variable_
- _Instance member function_
- _Instance member variable_
These elements are now using explicitly defined colors instead to fix the highlighting.
</div>
=> Fix wrong Type- and JavaScript highlighting inherited from parent scheme

src/nord.theme.json
Fixes #95
Related to #94
---
Before this PR, the background color of the marked entry in the completion popup when triggered while typing (enabled [“Show suggestions as you type“ option in preferences][1]) was the same like the background of the popup itself. As a result, the user did not know which entry was selected to complete the current line.
The problem only occurred when the completion popup was triggered while typing but not when being explicitly [invoked using the configured keymapping][2] (`Ctrl` / `⌃` + `Space` by default).
This was because the matching entry in the list, when invoked while typing, is _inactive_, but the color for inactive entries was the same like the background color of the popup itself.
This problem is now fixed by changing the color of the corresponding UI …
=> Fix invisible background color of inactive completion popup item

resources/themes/nord.xml
Related to #115, #116 
---
The `parent_scheme` is set automatically when a custom editor color scheme is created based on one of the bundled themes, like e.g. “Darcula“ when the IDE uses a dark theme or “Default“ in light mode.
Anyway, the attribute is not required at all and has been removed.
Moreover, to the time of this PR there's no real indicator in the [“IntelliJ IDEA Community Edition“ source code][1] that the attribute has any functionality but only [documenting the code base of the custom theme][2].
Nevertheless, it is possible that the attribute affects the logic how editor color schemes handle the inheritance of colors from other syntax definitions or the _Language Defaults_. There was an increasing amount of reported issues where syntax elements were highlighted with colors …
=> Remove unused `parent_scheme` attribute from root tag of editor scheme

resources/themes/nord.xml
Related to #69, #70, #77, #78, #108, #109, #115, #117, #119, #120
---
This PR implements the workaround documented in #120 to prevent more "random" color style breakages. It replaces all editor color scheme keys that inherit values from other keys with the explicit style definitions instead.
This causes the code of the editor scheme to increase drastically due to duplicate and repeated styles, but it currently the only way to work around this non-working style inheritance in the IDE theme API.
=> Replace all color inheritances with explicit definitions

resources/themes/nord.xml
=> Support new selected and inactive tab highlighting editor scheme keys

resources/themes/nord.xml
Closes #128 
Thanks to @Tom1206 for the report in https://github.com/arcticicestudio/nord-jetbrains/issues/120#issuecomment-585635441
---
</div>
=> Support background color styling of "diff" UI separator

resources/themes/nord.xml
=> Support highlighting of line number on caret row

resources/themes/nord.xml
=> Support highlighting of selected indent guide

resources/themes/nord.xml
=> Support highlighting of visual indent guide

resources/themes/nord.xml
=> Support new editor scheme key for runtime errors

resources/themes/nord.xml
=> Support highlighting of separator lines between editor and breadcrumbs

resources/themes/nord.xml
Closes #119, #129
---
<h3>Data Flow Controls</h3>
<h3>Markup Elements</h3>
<h3>JSON</h3>
</div>
=> Restore removed `parent_scheme` attribute

resources/themes/nord.xml
=> Fix editor & breadcrumbs separator line color

resources/themes/nord.xml
=> Fix highlighting of "injected language fragments"

resources/themes/nord.xml
Related to #120, #121
Closes #151
---
[PhpStorm][] ships with support for specific languages, frameworks and libraries for PHP development and of course advanced highlighting for [PHP][] itself. Due to the same problems like documented in #120 (mitigated in #121) some syntax theme keys required to be replaced with explicit definitions instead of relying on color inheritances.
Therefore this PR adds explicit support for PhpStorm's bundled language syntax:
1. Main support for [PHP][] and the [official JetBrains plugin][jb-plug-php]
2. [Laravel "Blade" Templates][blade]
See [JetBrains official “Blade“ documentation][jb-docs-blade] and [the plugin][jb-plug-blade] for more details.
3. "Twig" template engine
See [JetBrains official “Twig“ documentation][jb-docs-twig] and [the …
=> Add explicit support for bundled PhpStorm language syntax

resources/themes/nord.xml
Adjust the alpha of the background for diff inserted and modified blocks down to 50 to improve contrast with foreground (especially comments), and adjust diff deleted down to 80 as a minor improvement of the same.
Addresses issue: https://github.com/arcticicestudio/nord-jetbrains/issues/103
=> Reduce alpha value of patch background colors

resources/themes/nord.xml
Mostly this patch just sets Ruby styles to inherit from the generic styles, but some styles needed to be manually set to make it consistent with the rest of the theme.
Before:
After:
=> Add Ruby, RDoc and ERB language support

src/nord.theme.json
Add an explicit color overrides for JVM memory indicator (seems like "standard grey" from Darcula is used by default).
Initially I've tried to use `5e81ac` + `88c0d0` color combo, but it resulted in a badly readable memory numbers, so I decided to switch  `88c0d0` to a more "darker" `81a1c1`. Open to other color suggestions :)
Before:
After:
=> Override background for JVM memory indicator

src/nord.theme.json
Update background under context menu separator to make sure, that it matches overall menu background.
**Before:**
**After:**
P.S. [JetBrains documentation](https://github.com/JetBrains/intellij-community/blob/idea/213.6461.79/platform/platform-resources/src/themes/metadata/JDK.themeMetadata.json#L726) mentions, that `PopupMenu.background` is responsible for "Background under the context **or the main menu** separators", but I haven't noticed any issues with main menu before/any changes after my commit.
Closes #190
=> Update background under context menu separator

.eslintignore, .eslintrc.js, .husky/pre-commit, .npmrc, .prettierignore, .remarkignore, .remarkrc.mjs, changelog.md, lint-staged.config.js, package-lock.json, package.json, readme.md
With the retirement of the "Arctic Ice Studio" personal & Nord project brand [1] various migrations to the `svengreb` GitHub account [2] of other projects were also completed within the last weeks. There are also changes in Nord projects like `nordtheme/web` that other projects depended on and can now be adapted as well.
Therefore all Nord projects must adapt these changes which includes...
- the migration and repository name change of `arcticicestudio/nord-docs`[2] - all references must be updated.
- the migration of the `arcticicestudio/styleguide-git` repository to the `svengreb` "real-in-person" identity [3] - all references and used npm packages must be updated.
- the migration of the `arcticicestudio/styleguide-javascript` repository to the `svengreb` "real-in-person" identity [4] - …
=> Adapt remaining `arcticicestudio` "fade-out" changes
